import { prisma } from '@/db/prisma/client';

export type ReportType = 'student' | 'attendance' | 'finance' | 'academic' | 'exam';
export type ReportFormat = 'pdf' | 'csv' | 'excel';

export interface GeneratedReportArtifact {
  mimeType: string;
  filename: string;
  buffer: Buffer;
}

const buildCsv = (headers: string[], rows: (string | number | boolean | null | undefined)[][]): Buffer => {
  const escapeCell = (v: any): string => {
    if (v === null || v === undefined) return '';
    const s = String(v);
    if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  const lines: string[] = [];
  lines.push(headers.map(escapeCell).join(','));
  rows.forEach((row) => lines.push(row.map(escapeCell).join(',')));
  return Buffer.from('\uFEFF' + lines.join('\n'), 'utf-8');
};

const placeholderPdf = (title: string): Buffer => {
  const content = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>>>>>>>endobj
4 0 obj<</Length 120>>stream
BT /F1 24 Tf 72 720 Td (${title.replace(/[()]/g, '')}) Tj ET
BT /F1 12 Tf 72 690 Td (Generated by TZIT Education ERP & LMS Platform) Tj ET
BT /F1 10 Tf 72 670 Td (Full PDF rendering integration pending.) Tj ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000010 00000 n 
0000000053 00000 n 
0000000098 00000 n 
0000000213 00000 n 
trailer<</Size 5/Root 1 0 R>>
startxref
373
%%EOF`;
  return Buffer.from(content, 'latin1');
};

const getUserRoles = async (userId: string): Promise<string[]> => {
  const u = await prisma.user.findUnique({
    where: { id: userId },
    include: { userRoles: { include: { role: true } } },
  });
  return u?.userRoles.map((ur) => ur.role.name) || [];
};

export interface ReportFilterOptions {
  startDate?: string | null;
  endDate?: string | null;
}

const parseDateFilters = (opts?: ReportFilterOptions) => {
  const gte = opts?.startDate ? new Date(opts.startDate) : undefined;
  const lte = opts?.endDate ? new Date(`${opts.endDate}T23:59:59.999`) : undefined;
  if (!gte && !lte) return undefined;
  const out: Record<string, Date> = {};
  if (gte) out.gte = gte;
  if (lte) out.lte = lte;
  return out;
};

const mergeWhere = (base: any, extra: any) => {
  if (!extra) return base;
  if (!base) return extra;
  return { ...base, ...extra };
};

export class ReportService {
  static async generateReport(templateId: string, parameters: any, userId: string) {
    const template = await prisma.reportTemplate.findUnique({ where: { id: templateId } });
    if (!template) throw new Error('Template not found');

    const fileUrl = `https://storage.example.com/reports/${templateId}-${Date.now()}.pdf`;

    const generated = await prisma.generatedReport.create({
      data: {
        templateId,
        parameters: parameters || {},
        fileUrl,
        generatedAt: new Date(),
      },
    });

    return { generated, fileUrl };
  }

  static async listGeneratedReports(page = 1, limit = 20) {
    const skip = (page - 1) * limit;
    const reports = await prisma.generatedReport.findMany({ skip, take: limit, orderBy: { generatedAt: 'desc' } });
    const total = await prisma.generatedReport.count({ where: { deletedAt: null } });
    return { reports, pagination: { total, page, limit, totalPages: Math.ceil(total / limit) } };
  }

  static async exportReportByType(
    type: ReportType,
    format: ReportFormat,
    userId: string,
    opts?: ReportFilterOptions,
  ): Promise<GeneratedReportArtifact> {
    const roles = await getUserRoles(userId);
    const isAdmin = roles.some((r) => r === 'SuperAdmin' || r === 'Admin');
    const isTeacher = roles.includes('Teacher');
    const isStudent = roles.includes('Student');

    const csvToArtifact = (
      safeName: string,
      headers: string[],
      rows: (string | number | boolean | null | undefined)[][],
    ): GeneratedReportArtifact => {
      const csvBuffer = buildCsv(headers, rows);
      const suffix = opts?.startDate || opts?.endDate
        ? `_${opts.startDate || 'any'}_to_${opts.endDate || 'any'}`.replace(/[^a-zA-Z0-9_-]/g, '')
        : '';
      if (format === 'csv') {
        return {
          mimeType: 'text/csv; charset=utf-8',
          filename: `${safeName}${suffix}.csv`,
          buffer: csvBuffer,
        };
      }
      if (format === 'excel') {
        return {
          mimeType: 'application/vnd.ms-excel',
          filename: `${safeName}${suffix}.xls`,
          buffer: csvBuffer,
        };
      }
      return {
        mimeType: 'application/pdf',
        filename: `${safeName}${suffix}.pdf`,
        buffer: placeholderPdf(safeName),
      };
    };

    switch (type) {
      case 'student': {
        const take = 5000;
        const dateFilter = parseDateFilters(opts);
        const baseWhere: any = isStudent ? { userId } : {};
        const dateWhere: any = dateFilter ? { dateOfAdmission: dateFilter } : {};
        const students = await prisma.student.findMany({
          take,
          include: {
            user: { select: { firstName: true, lastName: true, email: true, phone: true } },
            batch: { select: { name: true } },
            department: { select: { name: true } },
          },
          orderBy: { createdAt: 'desc' },
          where: { ...baseWhere, ...dateWhere },
        });
        const headers = ['Student ID', 'First Name', 'Last Name', 'Email', 'Phone', 'Batch', 'Department', 'Status', 'Admission Date'];
        const rows = students.map((s: any) => [
          s.studentId || s.id,
          s.user?.firstName || '',
          s.user?.lastName || '',
          s.user?.email || '',
          s.user?.phone || '',
          s.batch?.name || s.batchId || '',
          s.department?.name || s.departmentId || '',
          s.isActive === false ? 'Inactive' : 'Active',
          s.dateOfAdmission ? new Date(s.dateOfAdmission).toLocaleDateString() : '',
        ]);
        return csvToArtifact('Student_Records', headers, rows);
      }

      case 'attendance': {
        const take = 5000;
        const dateFilter = parseDateFilters(opts);
        const baseWhere: any = isStudent ? { student: { userId } } : {};
        const dateWhere: any = dateFilter ? { attendanceDate: dateFilter } : {};
        const records = await prisma.attendanceRecord.findMany({
          take,
          include: {
            student: { include: { user: { select: { firstName: true, lastName: true } } } },
            course: { select: { title: true, code: true } },
          },
          orderBy: { attendanceDate: 'desc' },
          where: { ...baseWhere, ...dateWhere },
        });
        const headers = ['Date', 'Student ID', 'Student Name', 'Course', 'Status', 'Remarks'];
        const rows = records.map((r: any) => [
          r.attendanceDate ? new Date(r.attendanceDate).toLocaleDateString() : '',
          r.studentId,
          [r.student?.user?.firstName, r.student?.user?.lastName].filter(Boolean).join(' '),
          r.course?.code ? `${r.course.code} - ${r.course.title}` : r.course?.title || '',
          r.status || '',
          r.remarks || '',
        ]);
        return csvToArtifact('Attendance_Report', headers, rows);
      }

      case 'finance': {
        if (!isAdmin && !isTeacher && !isStudent) {
          return csvToArtifact('Finance_Report', ['Access'], [['Restricted to admin roles']]);
        }
        const dateFilter = parseDateFilters(opts);
        const baseWhere: any = isStudent ? { student: { userId } } : {};
        const dateWhere: any = dateFilter ? { dueDate: dateFilter } : {};
        const invoices = await prisma.invoice.findMany({
          take: 5000,
          include: {
            student: { include: { user: { select: { firstName: true, lastName: true } } } },
            payments: { select: { amount: true, method: true, paymentDate: true } },
          },
          where: { ...baseWhere, ...dateWhere },
          orderBy: { dueDate: 'desc' },
        });
        const headers = ['Invoice #', 'Student', 'Description', 'Amount', 'Paid', 'Balance', 'Due Date', 'Status', 'Last Payment'];
        const rows = invoices.map((inv: any) => {
          const paid = inv.payments.reduce((s: number, p: any) => s + (Number(p.amount) || 0), 0);
          const balance = Math.max(0, Number(inv.totalAmount || 0) - paid);
          return [
            inv.invoiceNumber || inv.id,
            [inv.student?.user?.firstName, inv.student?.user?.lastName].filter(Boolean).join(' ') || '',
            inv.description || '',
            Number(inv.totalAmount || 0),
            paid,
            balance,
            inv.dueDate ? new Date(inv.dueDate).toLocaleDateString() : '',
            inv.status || '',
            inv.payments?.[0]?.paymentDate ? new Date(inv.payments[0].paymentDate).toLocaleDateString() : '',
          ];
        });
        return csvToArtifact('Finance_Fees_Report', headers, rows);
      }

      case 'academic': {
        const dateFilter = parseDateFilters(opts);
        const dateWhere: any = dateFilter ? { createdAt: dateFilter } : {};
        const courses = await prisma.course.findMany({
          take: 1000,
          where: dateWhere,
          include: {
            _count: { select: { enrollments: true, exams: true } },
            teacherAssignment_course: {
              include: {
                teacher: {
                  include: {
                    user: { select: { firstName: true, lastName: true } },
                  },
                },
              },
            },
          },
          orderBy: { createdAt: 'desc' },
        });
        const headers = ['Course Code', 'Title', 'Teacher', 'Credits', 'Enrolled', 'Exams', 'Difficulty'];
        const rows = courses.map((c: any) => [
          c.code || '',
          c.title || '',
          c.teacherAssignment_course
            .map((tc: any) => [tc.teacher?.user?.firstName, tc.teacher?.user?.lastName].filter(Boolean).join(' '))
            .join('; ') || '',
          c.credits || '',
          c._count.enrollments,
          c._count.exams,
          c.difficultyLevel || '',
        ]);
        return csvToArtifact('Academic_Course_Performance', headers, rows);
      }

      case 'exam': {
        const dateFilter = parseDateFilters(opts);
        const baseWhere: any = { deletedAt: null };
        const dateWhere: any = dateFilter ? { createdAt: dateFilter } : {};
        const exams = await prisma.exam.findMany({
          take: 5000,
          where: { ...baseWhere, ...dateWhere },
          include: {
            course: { select: { title: true, code: true } },
            _count: { select: { examQuestions: true, attempts: true } },
          },
          orderBy: { createdAt: 'desc' },
        });
        const headers = ['Exam Title', 'Course', 'Questions', 'Attempts', 'Duration (min)', 'Passing Score', 'Start Date', 'End Date'];
        const rows = exams.map((e: any) => [
          e.title || '',
          e.course?.code ? `${e.course.code} - ${e.course.title}` : e.course?.title || '',
          e._count.examQuestions,
          e._count.attempts,
          e.durationMinutes || '',
          e.passingScore || '',
          e.startDate ? new Date(e.startDate).toLocaleDateString() : '',
          e.endDate ? new Date(e.endDate).toLocaleDateString() : '',
        ]);
        return csvToArtifact('Exams_and_Results', headers, rows);
      }

      default:
        return csvToArtifact('Report', ['Type'], [[type]]);
    }
  }
}

export default ReportService;

